import type { NextPage } from 'next';
import Head from 'next/head';

import Typography from '@mui/material/Typography';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Typography variant='h4'>Welcome to JWoC Admin</Typography>
    </div>
  );
};

export default Home;
